"use client";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, Zap } from "lucide-react";
import type { Session } from "@supabase/supabase-js";
import { messages, type Language } from "@/lib/i18n";
import { getStoredLanguage, storeLanguage } from "@/lib/language";
import { getSupabaseClient, isSupabaseConfigured } from "@/lib/supabase";
import { DashboardShell } from "./dashboard-shell";

type Screen = "landing" | "login" | "register";
type Profile = { name: string | null; email: string | null };
type PendingWorkspaceInvitation = { invitation_id: string; workspace_id: string; workspace_name: string; role: "admin" | "employee"; can_create_projects: boolean; can_edit_projects: boolean; can_create_tasks: boolean; can_assign_tasks: boolean; can_manage_users: boolean };
const activeWorkspaceKey = (userId: string) => `launchflow-active-workspace:${userId}`;

export function AuthGate() {
  const [language, setLanguage] = useState<Language>("en"); const [screen, setScreen] = useState<Screen>("landing"); const [session, setSession] = useState<Session | null>(null); const [profile, setProfile] = useState<Profile | null>(null); const [invitations, setInvitations] = useState<PendingWorkspaceInvitation[]>([]); const [activeWorkspaceId, setActiveWorkspaceId] = useState<string | null>(null); const [responding, setResponding] = useState(false); const [invitationNotice, setInvitationNotice] = useState(""); const [loadingSession, setLoadingSession] = useState(true); const t = messages[language];
  const updateLanguage = (nextLanguage: Language) => { storeLanguage(nextLanguage); setLanguage(nextLanguage); };
  useEffect(() => { setLanguage(getStoredLanguage()); }, []);
  useEffect(() => { document.documentElement.lang = language; }, [language]);
  useEffect(() => {
    if (!isSupabaseConfigured()) { setLoadingSession(false); return; }
    const supabase = getSupabaseClient();
    const updateSession = async (nextSession: Session | null) => { setSession(nextSession); if (!nextSession) { setProfile(null); setInvitations([]); setActiveWorkspaceId(null); setLoadingSession(false); return; } setLoadingSession(true); const [profileResult, invitationResult] = await Promise.all([supabase.from("profiles").select("name, email").eq("id", nextSession.user.id).maybeSingle(), supabase.rpc("get_my_pending_workspace_invitations")]); setProfile(profileResult.data); setInvitations((invitationResult.data ?? []) as PendingWorkspaceInvitation[]); setActiveWorkspaceId(window.localStorage.getItem(activeWorkspaceKey(nextSession.user.id))); setLoadingSession(false); };
    supabase.auth.getSession().then(({ data }) => void updateSession(data.session));
    const { data: listener } = supabase.auth.onAuthStateChange((_event, nextSession) => { void updateSession(nextSession); });
    return () => listener.subscription.unsubscribe();
  }, []);
  async function respondToInvitation(accept: boolean) { if (!session || invitations.length === 0) return; setResponding(true); setInvitationNotice(""); const invitation = invitations[0]; const { data, error } = await getSupabaseClient().rpc("respond_to_workspace_invitation", { target_invitation_id: invitation.invitation_id, accept_invitation: accept }); setResponding(false); if (error) { setInvitationNotice(t.invitations.responseError); return; } if (accept && data) { const workspaceId = String(data); window.localStorage.setItem(activeWorkspaceKey(session.user.id), workspaceId); setActiveWorkspaceId(workspaceId); } setInvitations(current => current.slice(1)); }
  if (loadingSession) return <div className="grid min-h-screen place-items-center bg-canvas text-sm text-slate-400">LaunchFlow</div>;
  if (session && invitations.length > 0) return <InvitationPrompt invitation={invitations[0]} language={language} setLanguage={updateLanguage} responding={responding} notice={invitationNotice} onAccept={() => respondToInvitation(true)} onDecline={() => respondToInvitation(false)} />;
  if (session) { const userName = profile?.name?.trim() || session.user.user_metadata.name?.trim() || profile?.email || session.user.email || "User"; const userEmail = profile?.email || session.user.email || ""; return <DashboardShell userId={session.user.id} userName={userName} userEmail={userEmail} activeWorkspaceId={activeWorkspaceId} language={language} setLanguage={updateLanguage} onLogout={() => getSupabaseClient().auth.signOut()} />; }
  return <AuthScreen screen={screen} setScreen={setScreen} language={language} setLanguage={updateLanguage} />;
}

function InvitationPrompt({ invitation, language, setLanguage, responding, notice, onAccept, onDecline }: { invitation: PendingWorkspaceInvitation; language: Language; setLanguage: (language: Language) => void; responding: boolean; notice: string; onAccept: () => void; onDecline: () => void }) {
  const t = messages[language];
  return <main className="grid min-h-screen place-items-center bg-canvas px-4 py-8"><section className="panel w-full max-w-md p-5 sm:p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-violet text-white"><Zap size={17} fill="currentColor" /></span><span className="font-semibold">LaunchFlow</span></div><LanguageToggle language={language} setLanguage={setLanguage} /></div><div className="mt-7"><p className="text-[10px] font-semibold uppercase tracking-wider text-violet">{t.invitations.title}</p><h1 className="mt-2 text-2xl font-bold tracking-tight">{t.invitations.invitedTo.replace("{workspace}", invitation.workspace_name)}</h1><p className="mt-3 text-xs leading-5 text-slate-400">{t.invitations.description}</p><div className="mt-4 rounded-lg border border-line bg-elevated px-3 py-2 text-xs text-slate-300"><span className="text-slate-500">{t.team.role}: </span>{invitation.role === "admin" ? t.common.admin : t.common.employee}</div></div>{notice && <p className="mt-4 rounded-lg bg-rose-400/10 px-3 py-2 text-xs text-rose-300">{notice}</p>}<div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button disabled={responding} onClick={onDecline} className="rounded-lg px-4 py-2.5 text-xs text-slate-300 hover:text-white disabled:opacity-60">{t.invitations.decline}</button><button disabled={responding} onClick={onAccept} className="rounded-lg bg-violet px-4 py-2.5 text-xs font-medium text-[#1d1035] disabled:opacity-60">{responding ? t.auth.loading : t.invitations.accept}</button></div></section></main>;
}

function AuthScreen({ screen, setScreen, language, setLanguage }: { screen: Screen; setScreen: (screen: Screen) => void; language: Language; setLanguage: (language: Language) => void }) {
  const t = messages[language]; const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [pending, setPending] = useState(false); const [notice, setNotice] = useState(""); const configured = isSupabaseConfigured();
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setNotice(""); if (!configured) { setNotice(t.auth.missingConfig); return; } setPending(true); const supabase = getSupabaseClient();
    const result = screen === "register" ? await supabase.auth.signUp({ email, password, options: { data: { name }, emailRedirectTo: `${window.location.origin}` } }) : await supabase.auth.signInWithPassword({ email, password });
    setPending(false); if (result.error) { setNotice(screen === "login" ? t.auth.invalidCredentials : result.error.message); return; } if (screen === "register" && !result.data.session) setNotice(t.auth.registrationSuccess);
  }
  if (screen === "landing") return <main className="min-h-screen bg-canvas px-4 py-5"><header className="mx-auto flex max-w-6xl items-center justify-between"><div className="flex items-center gap-2.5"><span className="grid h-8 w-8 place-items-center rounded-lg bg-violet text-white"><Zap size={17} fill="currentColor" /></span><span className="font-semibold tracking-tight">LaunchFlow</span></div><div className="flex items-center gap-2"><LanguageToggle language={language} setLanguage={setLanguage} /><button onClick={() => setScreen("login")} className="rounded-lg px-3 py-2 text-xs text-slate-300 hover:text-white">{t.auth.signIn}</button><button onClick={() => setScreen("register")} className="rounded-lg bg-violet px-3 py-2 text-xs font-medium text-[#1d1035]">{t.auth.getStarted}</button></div></header><section className="mx-auto grid max-w-6xl gap-10 py-20 lg:grid-cols-[1.1fr_.9fr] lg:py-32"><div className="max-w-xl"><span className="rounded-full bg-violet/15 px-3 py-1 text-[10px] font-medium text-violet">LaunchFlow Studio</span><h1 className="mt-5 text-4xl font-bold tracking-tight sm:text-5xl">{t.auth.landingTitle}</h1><p className="mt-5 max-w-lg text-sm leading-6 text-slate-400">{t.auth.landingText}</p><button onClick={() => setScreen("register")} className="mt-7 flex items-center gap-2 rounded-lg bg-violet px-4 py-2.5 text-sm font-medium text-[#1d1035]">{t.auth.getStarted}<ArrowRight size={16} /></button></div><div className="panel p-5"><p className="text-xs font-medium text-violet">{t.dashboard.projectProgress}</p><div className="mt-5 space-y-3">{[78, 62, 91].map((progress, index) => <div key={progress} className="rounded-lg bg-elevated p-3"><div className="flex justify-between text-xs"><span>{t.data.projects[index][0]}</span><span>{progress}%</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-700"><div className="h-full rounded-full bg-violet" style={{ width: `${progress}%` }} /></div></div>)}</div></div></section></main>;
  const isRegister = screen === "register";
  return <main className="grid min-h-screen place-items-center bg-canvas px-4 py-8"><section className="panel w-full max-w-md p-5 sm:p-6"><div className="flex items-center justify-between"><button onClick={() => setScreen("landing")} className="flex items-center gap-1 text-xs text-slate-400 hover:text-white"><ArrowLeft size={15} />{t.auth.back}</button><LanguageToggle language={language} setLanguage={setLanguage} /></div><div className="mt-7"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-violet text-white"><Zap size={17} fill="currentColor" /></span><span className="font-semibold">LaunchFlow</span></div><h1 className="mt-6 text-2xl font-bold">{isRegister ? t.auth.createAccount : t.auth.signInTitle}</h1><p className="mt-1 text-xs text-slate-400">{isRegister ? t.auth.createAccountText : t.auth.signInText}</p></div><form className="mt-6 space-y-4" onSubmit={submit}>{isRegister && <label className="block text-[11px] font-medium text-slate-300">{t.auth.name}<input value={name} onChange={event => setName(event.target.value)} required className="mt-1.5 h-10 w-full rounded-lg border border-line bg-elevated px-3 text-sm outline-none focus:border-violet" /></label>}<label className="block text-[11px] font-medium text-slate-300">{t.auth.email}<input value={email} onChange={event => setEmail(event.target.value)} required type="email" autoComplete="email" className="mt-1.5 h-10 w-full rounded-lg border border-line bg-elevated px-3 text-sm outline-none focus:border-violet" /></label><label className="block text-[11px] font-medium text-slate-300">{t.auth.password}<input value={password} onChange={event => setPassword(event.target.value)} required minLength={6} type="password" autoComplete={isRegister ? "new-password" : "current-password"} className="mt-1.5 h-10 w-full rounded-lg border border-line bg-elevated px-3 text-sm outline-none focus:border-violet" /></label>{notice && <p className={`rounded-lg px-3 py-2 text-xs ${notice === t.auth.registrationSuccess ? "bg-mint/10 text-mint" : "bg-rose-400/10 text-rose-300"}`}>{notice === t.auth.registrationSuccess && <CheckCircle2 className="mr-1 inline" size={14} />}{notice}</p>}<button disabled={pending} className="flex h-10 w-full items-center justify-center rounded-lg bg-violet text-sm font-medium text-[#1d1035] disabled:opacity-60">{pending ? t.auth.loading : isRegister ? t.auth.register : t.auth.login}</button></form><p className="mt-5 text-center text-xs text-slate-400">{isRegister ? t.auth.hasAccount : t.auth.noAccount} <button onClick={() => { setNotice(""); setScreen(isRegister ? "login" : "register"); }} className="text-violet hover:text-white">{isRegister ? t.auth.signIn : t.auth.signUp}</button></p></section></main>;
}

function LanguageToggle({ language, setLanguage }: { language: Language; setLanguage: (language: Language) => void }) { return <div className="rounded-lg bg-elevated p-1"><button onClick={() => setLanguage("en")} className={`rounded px-2 py-1 text-[10px] ${language === "en" ? "bg-slate-700 text-white" : "text-slate-400"}`}>EN</button><button onClick={() => setLanguage("es")} className={`rounded px-2 py-1 text-[10px] ${language === "es" ? "bg-slate-700 text-white" : "text-slate-400"}`}>ES</button></div>; }
