"use client";
import { useEffect, useState } from "react";
import { CheckCircle2, CircleGauge, ClipboardList, FolderKanban, Plus } from "lucide-react";
import { messages, type Language, type Translations } from "@/lib/i18n";
import { Sidebar } from "./sidebar";
import { Header } from "./header";
import { StatCard } from "./stat-card";
import { ProjectProgress } from "./project-card";
import { TaskStatus } from "./task-status";
import { TaskList } from "./task-list";
import { DeadlineList } from "./deadline-list";
import { TeamView } from "./team-view";
import { SettingsView } from "./settings-view";
import { getSupabaseClient } from "@/lib/supabase";
import { ProjectForm, ProjectsView, type Project, type ProjectInput } from "./projects-view";

type View = "dashboard" | "projects" | "tasks" | "team" | "settings";

function Dashboard({ t, userName, projects, canCreate, onNew, onViewAll }: { t: Translations; userName: string; projects: Project[]; canCreate: boolean; onNew: () => void; onViewAll: () => void }) {
  const activeProjects = projects.filter(project => project.status !== "completed").length;
  return <><section className="flex flex-col gap-4 py-2 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-bold tracking-tight">{t.dashboard.welcome.replace("{name}", userName)}</h1><span className="hidden items-center gap-1 rounded-full bg-mint/10 px-2 py-0.5 text-[9px] text-mint sm:flex"><i className="h-1.5 w-1.5 animate-pulse rounded-full bg-mint" />{t.dashboard.live}</span></div><p className="mt-1 max-w-xl text-xs leading-5 text-slate-400">{t.dashboard.subtitle}</p></div>{canCreate && <button onClick={onNew} className="flex h-9 w-fit items-center gap-1.5 rounded-lg bg-violet px-4 text-xs font-medium text-[#1d1035] transition hover:bg-[#ac8cff]"><Plus size={16} />{t.common.newProject}</button>}</section><section className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label={t.dashboard.activeProjects} value={String(activeProjects)} note={t.dashboard.thisMonth} icon={FolderKanban} accent="text-violet" /><StatCard label={t.dashboard.pendingTasks} value="0" note={t.tasks.empty} icon={ClipboardList} accent="text-blue" /><StatCard label={t.dashboard.completedTasks} value="0" note={t.tasks.empty} icon={CheckCircle2} accent="text-mint" /><StatCard label={t.dashboard.overallProgress} value="0%" note={t.tasks.empty} icon={CircleGauge} accent="text-violet" progress={0} /></section><section className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.65fr)_minmax(320px,.85fr)]"><ProjectProgress t={t} projects={projects} onViewAll={onViewAll} /><TaskStatus t={t} /></section><section className="mt-5 grid min-w-0 gap-4 xl:grid-cols-[minmax(0,1fr)_300px]"><TaskList t={t} /><DeadlineList t={t} projects={projects} /></section></>;
}

function ContentView({ view, t, userName, userEmail, projects, canCreate, canEdit, onNew, onEdit, onDelete, onViewAll }: { view: View; t: Translations; userName: string; userEmail: string; projects: Project[]; canCreate: boolean; canEdit: boolean; onNew: () => void; onEdit: (project: Project) => void; onDelete: (project: Project) => void; onViewAll: () => void }) {
  if (view === "team") return <TeamView t={t} userName={userName} userEmail={userEmail} />;
  if (view === "settings") return <SettingsView t={t} language="en" setLanguage={() => undefined} />;
  if (view === "projects") return <ProjectsView t={t} projects={projects} canCreate={canCreate} canEdit={canEdit} onNew={onNew} onEdit={onEdit} onDelete={onDelete} />;
  if (view === "tasks") return <section className="py-2"><h1 className="text-2xl font-bold tracking-tight">{t.tasks.title}</h1><p className="mt-1 text-xs leading-5 text-slate-400">{t.tasks.subtitle}</p><div className="mt-5"><TaskList t={t} /></div></section>;
  return <Dashboard t={t} userName={userName} projects={projects} canCreate={canCreate} onNew={onNew} onViewAll={onViewAll} />;
}

export function DashboardShell({ userId, userName, userEmail, language, setLanguage, onLogout }: { userId: string; userName: string; userEmail: string; language: Language; setLanguage: (language: Language) => void; onLogout: () => Promise<{ error: Error | null }> }) {
  const [menuOpen, setMenuOpen] = useState(false); const [view, setView] = useState<View>("dashboard"); const [projects, setProjects] = useState<Project[]>([]); const [workspaceId, setWorkspaceId] = useState<string | null>(null); const [role, setRole] = useState<"admin" | "employee" | null>(null); const [canCreate, setCanCreate] = useState(false); const [canEdit, setCanEdit] = useState(false); const [editing, setEditing] = useState<Project | null | undefined>(); const [submitting, setSubmitting] = useState(false); const [notice, setNotice] = useState(""); const t = messages[language]; const initials = userName.split(/\s+/).map(part => part[0]).join("").slice(0, 2).toUpperCase() || "U";
  useEffect(() => { const load = async () => { const supabase = getSupabaseClient(); const { data: member, error: memberError } = await supabase.from("workspace_members").select("workspace_id, role, can_create_projects, can_edit_projects").eq("user_id", userId).limit(1).maybeSingle(); if (memberError || !member) { setNotice(t.projects.loadError); return; } const memberRole = String(member.role).toLowerCase() as "admin" | "employee"; const isAdmin = memberRole === "admin"; setWorkspaceId(member.workspace_id); setRole(memberRole); setCanCreate(isAdmin || Boolean(member.can_create_projects)); setCanEdit(isAdmin || Boolean(member.can_edit_projects)); const { data, error } = await supabase.from("projects").select("id, workspace_id, name, description, status, priority, due_date, created_at").eq("workspace_id", member.workspace_id).order("created_at", { ascending: false }); if (error) setNotice(t.projects.loadError); else setProjects((data ?? []) as Project[]); }; void load(); }, [userId, t.projects.loadError]);
  async function saveProject(input: ProjectInput) { if (!input.name) { setNotice(t.projects.required); return; } setSubmitting(true); const supabase = getSupabaseClient(); const result = editing ? await supabase.from("projects").update(input).eq("id", editing.id).select("id, workspace_id, name, description, status, priority, due_date, created_at").single() : await supabase.from("projects").insert({ ...input, workspace_id: workspaceId, created_by: userId, status: "planning" }).select("id, workspace_id, name, description, status, priority, due_date, created_at").single(); setSubmitting(false); if (result.error || !result.data) { setNotice(t.projects.saveError); return; } setProjects(current => editing ? current.map(project => project.id === editing.id ? result.data as Project : project) : [result.data as Project, ...current]); setNotice(editing ? t.projects.updatedSuccess : t.projects.createdSuccess); setEditing(undefined); }
  async function deleteProject(project: Project) { if (!window.confirm(t.projects.deleteConfirm)) return; const { error } = await getSupabaseClient().from("projects").delete().eq("id", project.id); if (error) { setNotice(t.projects.deleteError); return; } setProjects(current => current.filter(item => item.id !== project.id)); setNotice(t.projects.deletedSuccess); }
  const content = view === "settings" ? <SettingsView t={t} language={language} setLanguage={setLanguage} onLogout={onLogout} userName={userName} userEmail={userEmail} /> : <ContentView view={view} t={t} userName={userName} userEmail={userEmail} projects={projects} canCreate={canCreate} canEdit={canEdit} onNew={() => setEditing(null)} onEdit={setEditing} onDelete={deleteProject} onViewAll={() => setView("projects")} />;
  return <div className="min-h-screen bg-canvas"><Sidebar open={menuOpen} close={() => setMenuOpen(false)} active={view} setActive={setView} t={t} onLogout={onLogout} userName={userName} initials={initials} role={role} /><Header openMenu={() => setMenuOpen(true)} language={language} setLanguage={setLanguage} t={t} userName={userName} initials={initials} /><main className="pt-16 lg:pl-60"><div className="mx-auto max-w-[1600px] p-4 lg:p-5">{notice && <p className="mb-3 rounded-lg bg-mint/10 px-3 py-2 text-xs text-mint">{notice}</p>}{content}</div></main>{editing !== undefined && <ProjectForm t={t} project={editing} submitting={submitting} onClose={() => setEditing(undefined)} onSubmit={saveProject} />}</div>;
}
