"use client";

import { useEffect, useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import { isWorkspaceView, type WorkspaceView } from "@/lib/navigation";
import { CheckCircle2, CircleGauge, ClipboardList, FolderKanban, Plus } from "lucide-react";
import { messages, type Language, type Translations } from "@/lib/i18n";
import { getSupabaseClient } from "@/lib/supabase";
import { Sidebar } from "./sidebar";
import { Header } from "./header";
import { StatCard } from "./stat-card";
import { ProjectProgress } from "./project-card";
import { TaskStatus } from "./task-status";
import { TaskList } from "./task-list";
import { DeadlineList } from "./deadline-list";
import { TeamView, type InvitationInput, type MemberUpdate, type TeamInvitation, type TeamMember } from "./team-view";
import { SettingsView } from "./settings-view";
import { ProjectForm, ProjectsView, type Project, type ProjectInput } from "./projects-view";
import { TaskForm, TasksView, type Task, type TaskInput, type WorkspaceMember } from "./tasks-view";

function Dashboard({ t, userName, userId, projects, tasks, members, canCreateProject, canCreateTask, canEditProject, canDeleteTask, canEditTask, canChangeTaskStatus, onNewProject, onNewTask, onViewAll, onOpenProject, onEditProject, onDeleteProject, onOpenTask, onDeleteTask, onStatusChange }: { t: Translations; userName: string; userId: string; projects: Project[]; tasks: Task[]; members: WorkspaceMember[]; canCreateProject: boolean; canCreateTask: boolean; canEditProject: boolean; canDeleteTask: boolean; canEditTask: (task: Task) => boolean; canChangeTaskStatus: (task: Task) => boolean; onNewProject: () => void; onNewTask: () => void; onViewAll: () => void; onOpenProject: (project: Project) => void; onEditProject: (project: Project) => void; onDeleteProject: (project: Project) => void; onOpenTask: (task: Task) => void; onDeleteTask: (task: Task) => void; onStatusChange: (task: Task, status: Task["status"]) => void }) {
  const activeProjects = projects.filter(project => project.status !== "completed").length;
  const pendingTasks = tasks.filter(task => task.status !== "completed").length;
  const completedTasks = tasks.filter(task => task.status === "completed").length;
  const progress = tasks.length ? Math.round(completedTasks / tasks.length * 100) : 0;
  const assignedTasks = tasks.filter(task => task.assignee_id === userId);
  return <><section className="flex flex-col gap-4 py-2 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-bold tracking-tight">{t.dashboard.welcome.replace("{name}", userName)}</h1><span className="hidden items-center gap-1 rounded-full bg-mint/10 px-2 py-0.5 text-[9px] text-mint sm:flex"><i className="h-1.5 w-1.5 animate-pulse rounded-full bg-mint" />{t.dashboard.live}</span></div><p className="mt-1 max-w-xl text-xs leading-5 text-slate-400">{t.dashboard.subtitle}</p></div>{canCreateProject && <button onClick={onNewProject} className="flex h-9 w-fit items-center gap-1.5 rounded-lg bg-violet px-4 text-xs font-medium text-[#1d1035] transition hover:bg-[#ac8cff]"><Plus size={16} />{t.common.newProject}</button>}</section><section className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label={t.dashboard.activeProjects} value={String(activeProjects)} note={t.dashboard.thisMonth} icon={FolderKanban} accent="text-violet" /><StatCard label={t.dashboard.pendingTasks} value={String(pendingTasks)} note={t.dashboard.totalTasks} icon={ClipboardList} accent="text-blue" /><StatCard label={t.dashboard.completedTasks} value={String(completedTasks)} note={t.dashboard.totalTasks} icon={CheckCircle2} accent="text-mint" /><StatCard label={t.dashboard.overallProgress} value={`${progress}%`} note={tasks.length ? t.dashboard.totalTasks : t.tasks.empty} icon={CircleGauge} accent="text-violet" progress={progress} /></section><section className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.65fr)_minmax(320px,.85fr)]"><ProjectProgress t={t} projects={projects} tasks={tasks} canEdit={canEditProject} onViewAll={onViewAll} onOpen={onOpenProject} onEdit={onEditProject} onDelete={onDeleteProject} /><TaskStatus t={t} tasks={tasks} /></section><section className="mt-5 grid min-w-0 gap-4 xl:grid-cols-[minmax(0,1fr)_300px]"><TaskList t={t} tasks={assignedTasks} projects={projects} members={members} canCreate={canCreateTask} canEditTask={canEditTask} canDelete={canDeleteTask} canChangeStatus={canChangeTaskStatus} onNew={onNewTask} onOpen={onOpenTask} onDelete={onDeleteTask} onStatusChange={onStatusChange} /><DeadlineList t={t} projects={projects} tasks={tasks} /></section></>;
}

export function DashboardShell({ userId, userName: initialUserName, userEmail, activeWorkspaceId, language, setLanguage, onLogout }: { userId: string; userName: string; userEmail: string; activeWorkspaceId: string | null; language: Language; setLanguage: (language: Language) => void; onLogout: () => Promise<{ error: Error | null }> }) {
  const [userName, setUserName] = useState(initialUserName);
  const [workspaceName, setWorkspaceName] = useState<string | null>(null);
  useEffect(() => { setUserName(initialUserName); }, [initialUserName]);
  const pathname = usePathname();
  const router = useRouter();
  const section = pathname.split("/")[1];
  const view: WorkspaceView = isWorkspaceView(section) ? section : "dashboard";
  const setView = (nextView: WorkspaceView) => router.push(`/${nextView}`, { scroll: false });
  useEffect(() => {
    if (pathname === "/") router.replace("/dashboard", { scroll: false });
  }, [pathname, router]);
  const [menuOpen, setMenuOpen] = useState(false); const [projectTaskFocus, setProjectTaskFocus] = useState<string | null>(null); const [projects, setProjects] = useState<Project[]>([]); const [tasks, setTasks] = useState<Task[]>([]); const [teamMembers, setTeamMembers] = useState<TeamMember[]>([]); const [invitations, setInvitations] = useState<TeamInvitation[]>([]); const [workspaceId, setWorkspaceId] = useState<string | null>(null); const [role, setRole] = useState<"admin" | "employee" | null>(null); const [canCreateProject, setCanCreateProject] = useState(false); const [canEditProject, setCanEditProject] = useState(false); const [canCreateTask, setCanCreateTask] = useState(false); const [canAssignTask, setCanAssignTask] = useState(false); const [canManageUsers, setCanManageUsers] = useState(false); const [emailSendingInvitationId, setEmailSendingInvitationId] = useState<string | null>(null); const [projectEditing, setProjectEditing] = useState<Project | null | undefined>(); const [taskEditing, setTaskEditing] = useState<Task | null | undefined>(); const [submitting, setSubmitting] = useState(false); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState(""); const t = messages[language]; const initials = userName.split(/\s+/).map(part => part[0]).join("").slice(0, 2).toUpperCase() || "U"; const isAdmin = role === "admin"; const members: WorkspaceMember[] = teamMembers.map(member => ({ user_id: member.user_id, name: member.name, email: member.email }));

  useEffect(() => { const load = async () => { setLoading(true); setWorkspaceName(null); const supabase = getSupabaseClient(); const { data: memberRows, error: memberError } = await supabase.from("workspace_members").select("workspace_id, role, can_create_projects, can_edit_projects, can_create_tasks, can_assign_tasks, can_manage_users, created_at").eq("user_id", userId).order("created_at", { ascending: false }); const member = memberRows?.find(item => item.workspace_id === activeWorkspaceId) ?? memberRows?.[0]; if (memberError || !member) { setNotice(t.team.loadError); setLoading(false); return; } const memberRole = String(member.role).toLowerCase() as "admin" | "employee"; const admin = memberRole === "admin"; const manageUsers = admin || Boolean(member.can_manage_users); setWorkspaceId(member.workspace_id); setRole(memberRole); setCanCreateProject(admin || Boolean(member.can_create_projects)); setCanEditProject(admin || Boolean(member.can_edit_projects)); setCanCreateTask(admin || Boolean(member.can_create_tasks)); setCanAssignTask(admin || Boolean(member.can_assign_tasks)); setCanManageUsers(manageUsers); const [projectResult, taskResult, workspaceResult] = await Promise.all([supabase.from("projects").select("id, workspace_id, name, description, status, priority, due_date, created_at").eq("workspace_id", member.workspace_id).order("created_at", { ascending: false }), supabase.from("tasks").select("id, workspace_id, project_id, title, description, status, priority, assignee_id, due_date, created_by, created_at").eq("workspace_id", member.workspace_id).order("created_at", { ascending: false }), supabase.from("workspaces").select("name").eq("id", member.workspace_id).single()]); if (workspaceResult.error || !workspaceResult.data) setNotice(t.settings.loadError); else setWorkspaceName(workspaceResult.data.name); if (projectResult.error) setNotice(t.projects.loadError); else setProjects((projectResult.data ?? []) as Project[]); if (taskResult.error) setNotice(t.tasks.loadError); else setTasks((taskResult.data ?? []) as Task[]); await refreshTeam(member.workspace_id, manageUsers); setLoading(false); }; void load(); }, [userId, activeWorkspaceId, t.projects.loadError, t.tasks.loadError, t.team.loadError, t.settings.loadError]);

  useEffect(() => { if (view !== "tasks") setProjectTaskFocus(null); }, [view]);

  async function saveWorkspaceName(name: string) {
    const trimmedName = name.trim();
    if (!isAdmin || !workspaceId || workspaceName === null || !trimmedName) throw new Error("WORKSPACE_UPDATE_NOT_ALLOWED");
    const { data, error } = await getSupabaseClient().from("workspaces")
      .update({ name: trimmedName }).eq("id", workspaceId).select("name").single();
    if (error || !data) throw new Error("WORKSPACE_UPDATE_FAILED");
    setWorkspaceName(data.name);
  }

  async function saveProfileName(name: string) {
    const trimmedName = name.trim();
    if (!trimmedName) throw new Error("PROFILE_NAME_REQUIRED");
    const { data, error } = await getSupabaseClient().from("profiles")
      .update({ name: trimmedName }).eq("id", userId).select("name").single();
    if (error || !data) throw new Error("PROFILE_UPDATE_FAILED");
    setUserName(data.name);
    setTeamMembers(current => current.map(member => member.user_id === userId ? { ...member, name: data.name } : member));
  }

  async function refreshTeam(targetWorkspaceId = workspaceId, canManage = canManageUsers) { if (!targetWorkspaceId) return; const supabase = getSupabaseClient(); const memberResult = await supabase.from("workspace_members").select("id, workspace_id, user_id, role, can_create_projects, can_edit_projects, can_create_tasks, can_assign_tasks, can_manage_users").eq("workspace_id", targetWorkspaceId).order("created_at", { ascending: true }); if (memberResult.error) { setNotice(t.team.loadError); return; } const records = memberResult.data ?? []; const userIds = records.map(item => item.user_id); const { data: profiles, error: profileError } = userIds.length ? await supabase.from("profiles").select("id, name, email").in("id", userIds) : { data: [], error: null }; if (profileError) { setNotice(t.team.loadError); return; } const profileMap = new Map((profiles ?? []).map(profile => [profile.id, profile])); setTeamMembers(records.map(record => ({ ...record, role: record.role as "admin" | "employee", name: profileMap.get(record.user_id)?.name ?? "", email: profileMap.get(record.user_id)?.email ?? "" })) as TeamMember[]); if (canManage) { const invitationResult = await supabase.from("workspace_invitations").select("id, email, role, status, can_create_projects, can_edit_projects, can_create_tasks, can_assign_tasks, can_manage_users").eq("workspace_id", targetWorkspaceId).eq("status", "pending").order("created_at", { ascending: false }); if (!invitationResult.error) setInvitations((invitationResult.data ?? []) as TeamInvitation[]); } else setInvitations([]); }

  async function updateMember(member: TeamMember, value: MemberUpdate) { if (!canManageUsers || (!isAdmin && (member.role === "admin" || member.user_id === userId))) return; const safeValue = isAdmin ? value : { ...value, role: "employee" as const }; setSubmitting(true); const { error } = await getSupabaseClient().from("workspace_members").update(safeValue).eq("id", member.id).eq("workspace_id", member.workspace_id); setSubmitting(false); if (error) { setNotice(t.team.saveError); return; } await refreshTeam(); setNotice(t.team.updatedSuccess); }
  async function removeMember(member: TeamMember) { if (!canManageUsers || (!isAdmin && (member.role === "admin" || member.user_id === userId)) || !window.confirm(t.team.removeConfirm.replace("{name}", member.name || member.email))) return; setSubmitting(true); const { error } = await getSupabaseClient().from("workspace_members").delete().eq("id", member.id).eq("workspace_id", member.workspace_id); setSubmitting(false); if (error) { setNotice(t.team.removeError); return; } await refreshTeam(); setNotice(t.team.removedSuccess); }
  async function sendInvitationEmail(invitationId: string, successMessage: string) { if (!canManageUsers || emailSendingInvitationId) return; setEmailSendingInvitationId(invitationId); try { const { error } = await getSupabaseClient().functions.invoke("send-workspace-invitation", { body: { invitation_id: invitationId } }); setNotice(error ? t.team.emailDeliveryFailed : successMessage); } catch { setNotice(t.team.emailDeliveryFailed); } finally { setEmailSendingInvitationId(null); } }
  async function inviteMember(input: InvitationInput) { if (!canManageUsers || !workspaceId) return; const safeInput = isAdmin ? input : { ...input, role: "employee" as const }; setSubmitting(true); const { data, error } = await getSupabaseClient().from("workspace_invitations").insert({ ...safeInput, workspace_id: workspaceId, invited_by: userId, status: "pending" }).select("id, email, role, status, can_create_projects, can_edit_projects, can_create_tasks, can_assign_tasks, can_manage_users").single(); if (error || !data) { setSubmitting(false); setNotice(t.team.invitationError); return; } await refreshTeam(); await sendInvitationEmail(String(data.id), t.team.invitationSent); setSubmitting(false); }
  async function resendInvitationEmail(invitation: TeamInvitation) { await sendInvitationEmail(invitation.id, t.team.emailSentSuccess); }
  async function cancelInvitation(invitation: TeamInvitation) { if (!canManageUsers || (!isAdmin && invitation.role === "admin") || !window.confirm(t.team.cancelInvitationConfirm.replace("{email}", invitation.email))) return; const { error } = await getSupabaseClient().from("workspace_invitations").delete().eq("id", invitation.id); if (error) { setNotice(t.team.invitationError); return; } await refreshTeam(); setNotice(t.team.invitationCancelled); }

  async function refreshProjectsAndTasks() { if (!workspaceId) return; const supabase = getSupabaseClient(); const [projectResult, taskResult] = await Promise.all([supabase.from("projects").select("id, workspace_id, name, description, status, priority, due_date, created_at").eq("workspace_id", workspaceId).order("created_at", { ascending: false }), supabase.from("tasks").select("id, workspace_id, project_id, title, description, status, priority, assignee_id, due_date, created_by, created_at").eq("workspace_id", workspaceId).order("created_at", { ascending: false })]); if (projectResult.error || taskResult.error) { setNotice(projectResult.error ? t.projects.loadError : t.tasks.loadError); return; } setProjects((projectResult.data ?? []) as Project[]); setTasks((taskResult.data ?? []) as Task[]); }

  async function saveProject(input: ProjectInput) { if ((projectEditing ? !canEditProject : !canCreateProject) || !workspaceId) return; if (!input.name) { setNotice(t.projects.required); return; } setSubmitting(true); const supabase = getSupabaseClient(); const result = projectEditing ? await supabase.from("projects").update(input).eq("id", projectEditing.id).eq("workspace_id", workspaceId).select("id").single() : await supabase.from("projects").insert({ ...input, workspace_id: workspaceId, created_by: userId, status: "planning" }).select("id").single(); setSubmitting(false); if (result.error || !result.data) { setNotice(t.projects.saveError); return; } await refreshProjectsAndTasks(); setNotice(projectEditing ? t.projects.updatedSuccess : t.projects.createdSuccess); setProjectEditing(undefined); }
  async function deleteProject(project: Project) { if (!canEditProject || !workspaceId || !window.confirm(t.projects.deleteConfirm)) return; const { error } = await getSupabaseClient().from("projects").delete().eq("id", project.id).eq("workspace_id", workspaceId); if (error) { setNotice(t.projects.deleteError); return; } await refreshProjectsAndTasks(); setNotice(t.projects.deletedSuccess); }
  const canEditTask = (task: Task) => isAdmin || (task.created_by === userId && canCreateTask);
  const canChangeTaskStatus = (task: Task) => canEditTask(task) || task.assignee_id === userId;
  async function saveTask(input: TaskInput) { if ((taskEditing ? !canEditTask(taskEditing) && !canAssignTask : !canCreateTask) || !workspaceId) return; if (!input.title || !input.project_id) { setNotice(t.tasks.required); return; } setSubmitting(true); const safeInput = canAssignTask ? input : { ...input, assignee_id: taskEditing?.assignee_id ?? null }; const supabase = getSupabaseClient(); const result = taskEditing ? await supabase.from("tasks").update(safeInput).eq("id", taskEditing.id).eq("workspace_id", workspaceId).select("id").single() : await supabase.from("tasks").insert({ ...safeInput, workspace_id: workspaceId, created_by: userId }).select("id").single(); setSubmitting(false); if (result.error || !result.data) { setNotice(t.tasks.saveError); return; } await refreshProjectsAndTasks(); setNotice(taskEditing ? t.tasks.updatedSuccess : t.tasks.createdSuccess); setTaskEditing(undefined); }
  async function deleteTask(task: Task) { if (!isAdmin || !workspaceId || !window.confirm(t.tasks.deleteConfirm)) return; const { error } = await getSupabaseClient().from("tasks").delete().eq("id", task.id).eq("workspace_id", workspaceId); if (error) { setNotice(t.tasks.deleteError); return; } await refreshProjectsAndTasks(); setNotice(t.tasks.deletedSuccess); }
  async function changeTaskStatus(task: Task, status: Task["status"]) { if (!workspaceId || !canChangeTaskStatus(task) || status === task.status) return; const { error } = await getSupabaseClient().from("tasks").update({ status }).eq("id", task.id).eq("workspace_id", workspaceId); if (error) { setNotice(t.tasks.saveError); return; } await refreshProjectsAndTasks(); setNotice(t.tasks.updatedSuccess); }
  async function toggleTask(task: Task) { await changeTaskStatus(task, task.status === "completed" ? "pending" : "completed"); }

  const canOpenTask = (task: Task) => canEditTask(task) || canAssignTask;
  const noticeIsError = new Set<string>([t.settings.loadError, t.team.loadError, t.team.saveError, t.team.removeError, t.team.invitationError, t.team.emailDeliveryFailed, t.projects.loadError, t.projects.saveError, t.projects.deleteError, t.tasks.loadError, t.tasks.saveError, t.tasks.deleteError]).has(notice);
  let content; if (loading) content = <div className="panel p-5 text-sm text-slate-400">{t.auth.loading}</div>; else if (view === "settings") content = <SettingsView key={workspaceId} workspaceName={workspaceName ?? ""} canEditWorkspace={isAdmin && workspaceName !== null} onSaveWorkspaceName={saveWorkspaceName} onSaveProfileName={saveProfileName} t={t} language={language} setLanguage={setLanguage} onLogout={onLogout} userName={userName} userEmail={userEmail} />; else if (view === "team") content = <TeamView t={t} members={teamMembers} invitations={invitations} currentUserId={userId} isAdmin={isAdmin} canManageUsers={canManageUsers} emailSendingInvitationId={emailSendingInvitationId} submitting={submitting} onUpdate={updateMember} onRemove={removeMember} onInvite={inviteMember} onResendInvitation={resendInvitationEmail} onCancelInvitation={cancelInvitation} />; else if (view === "projects") content = <ProjectsView t={t} projects={projects} canCreate={canCreateProject} canEdit={canEditProject} onNew={() => setProjectEditing(null)} onEdit={setProjectEditing} onDelete={deleteProject} />; else if (view === "tasks") content = <TasksView t={t} tasks={projectTaskFocus ? tasks.filter(task => task.project_id === projectTaskFocus) : tasks} projects={projects} members={members} canCreate={canCreateTask} canEditTask={canOpenTask} canChangeStatus={canChangeTaskStatus} canDelete={isAdmin} onNew={() => setTaskEditing(null)} onEdit={setTaskEditing} onDelete={deleteTask} onToggle={toggleTask} />; else content = <Dashboard t={t} userName={userName} userId={userId} projects={projects} tasks={tasks} members={members} canCreateProject={canCreateProject} canCreateTask={canCreateTask} canEditProject={canEditProject} canDeleteTask={isAdmin} canEditTask={canOpenTask} canChangeTaskStatus={canChangeTaskStatus} onNewProject={() => setProjectEditing(null)} onNewTask={() => setTaskEditing(null)} onViewAll={() => setView("projects")} onOpenProject={project => { setProjectTaskFocus(project.id); setView("tasks"); }} onEditProject={setProjectEditing} onDeleteProject={deleteProject} onOpenTask={setTaskEditing} onDeleteTask={deleteTask} onStatusChange={(task, status) => void changeTaskStatus(task, status)} />;
  return <div className="min-h-screen bg-canvas"><Sidebar workspaceName={workspaceName ?? "—"} open={menuOpen} close={() => setMenuOpen(false)} active={view} t={t} onLogout={onLogout} userName={userName} initials={initials} role={role} /><Header openMenu={() => setMenuOpen(true)} language={language} setLanguage={setLanguage} t={t} userName={userName} initials={initials} role={role} canCreateProject={canCreateProject} onNewProject={() => setProjectEditing(null)} /><main className="pt-16 lg:pl-60"><div className="mx-auto max-w-[1600px] p-4 lg:p-5">{notice && <p className={`mb-3 rounded-lg px-3 py-2 text-xs ${noticeIsError ? "bg-rose-400/10 text-rose-300" : "bg-mint/10 text-mint"}`}>{notice}</p>}{content}</div></main>{projectEditing !== undefined && <ProjectForm t={t} project={projectEditing} submitting={submitting} onClose={() => setProjectEditing(undefined)} onSubmit={saveProject} />}{taskEditing !== undefined && <TaskForm t={t} task={taskEditing} projects={projectTaskFocus ? [...projects.filter(project => project.id === projectTaskFocus), ...projects.filter(project => project.id !== projectTaskFocus)] : projects} members={members} canAssign={canAssignTask} canEditDetails={!taskEditing || canEditTask(taskEditing)} submitting={submitting} onClose={() => setTaskEditing(undefined)} onSubmit={saveTask} />}</div>;
}
