import { CalendarClock } from "lucide-react";
import type { Translations } from "@/lib/i18n";
import type { Project } from "./projects-view";
import type { Task } from "./tasks-view";

export function DeadlineList({ t, projects, tasks }: { t: Translations; projects: Project[]; tasks: Task[] }) {
  const deadlines = [...projects.filter(project => project.due_date && project.status !== "completed").map(project => ({ id: `project-${project.id}`, title: project.name, dueDate: project.due_date!, type: t.tasks.projectDeadline })), ...tasks.filter(task => task.due_date && task.status !== "completed").map(task => ({ id: `task-${task.id}`, title: task.title, dueDate: task.due_date!, type: t.tasks.taskDeadline }))].sort((a, b) => a.dueDate.localeCompare(b.dueDate)).slice(0, 5);
  return <aside className="panel ambient-card p-5"><div className="flex items-center justify-between"><h2 className="section-title">{t.dashboard.deadlines}</h2><CalendarClock size={16} className="text-slate-400" /></div><p className="mt-1 text-xs text-slate-400">{t.dashboard.deadlineSubtitle}</p>{deadlines.length === 0 ? <div className="empty-state"><span className="empty-icon"><CalendarClock size={22} /></span><p className="text-xs text-slate-400">{t.common.noItems}</p></div> : <div className="mt-4 space-y-2">{deadlines.map(item => <div key={item.id} className="flex items-center gap-3 rounded-xl border border-line bg-white/[.02] p-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-violet/15 text-violet"><CalendarClock size={16} /></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium">{item.title}</p><p className="text-[11px] text-slate-400">{item.type}</p></div><span className="whitespace-nowrap text-[11px] text-slate-300">{new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(`${item.dueDate}T00:00:00`))}</span></div>)}</div>}</aside>;
}
