import { Bell, Menu, Plus, Search } from "lucide-react";
import type { Language, Translations } from "@/lib/i18n";
import { Avatar } from "./avatar";

export function Header({ openMenu, language, setLanguage, t, userName, initials }: { openMenu: () => void; language: Language; setLanguage: (language: Language) => void; t: Translations; userName: string; initials: string }) {
  return <header className="fixed left-0 right-0 top-0 z-30 flex h-16 items-center gap-3 border-b border-line bg-canvas/85 px-4 backdrop-blur-xl lg:left-60 lg:px-5">
    <button onClick={openMenu} className="icon-button lg:hidden" aria-label={t.common.openMenu}><Menu size={18} /></button><div className="relative hidden w-full max-w-[360px] sm:block"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" size={16} /><input aria-label={t.common.search} className="h-9 w-full rounded-lg border border-line bg-panel pl-9 pr-12 text-xs outline-none placeholder:text-slate-500 focus:border-violet focus:ring-1 focus:ring-violet" placeholder={t.common.search} /><kbd className="absolute right-3 top-1/2 -translate-y-1/2 text-[10px] text-slate-500">⌘K</kbd></div>
    <div className="ml-auto flex items-center gap-2"><div className="hidden rounded-lg bg-elevated p-1 sm:flex"><button onClick={() => setLanguage("en")} aria-label="English" className={`rounded px-2 py-1 text-[10px] ${language === "en" ? "bg-slate-700 text-white" : "text-slate-400"}`}>EN</button><button onClick={() => setLanguage("es")} aria-label="Español" className={`rounded px-2 py-1 text-[10px] ${language === "es" ? "bg-slate-700 text-white" : "text-slate-400"}`}>ES</button></div><button className="icon-button relative" aria-label={t.common.notifications}><Bell size={17} /><i className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-rose-400" /></button><button className="flex h-9 items-center gap-1.5 rounded-lg bg-violet px-3 text-xs font-medium text-[#1d1035] transition hover:bg-[#ac8cff]"><Plus size={16} /><span className="hidden xs:inline">{t.common.newProject}</span></button><div className="ml-1 flex items-center gap-2"><Avatar initials={initials} color="#4c1d95" /><div className="hidden xl:block"><p className="text-xs font-medium leading-tight">{userName}</p><p className="text-[10px] text-slate-400">{t.common.admin}</p></div></div></div>
  </header>;
}
