import { CalendarDays, Eye, FolderKanban, Pencil, Trash2 } from "lucide-react";
import type { Translations } from "@/lib/i18n";
import { ProgressBar } from "./progress-bar";
import type { Project } from "./projects-view";
import type { Task } from "./tasks-view";

export function ProjectProgress({ t, projects, tasks, canEdit, onViewAll, onOpen, onEdit, onDelete }: { t: Translations; projects: Project[]; tasks: Task[]; canEdit: boolean; onViewAll?: () => void; onOpen: (project: Project) => void; onEdit: (project: Project) => void; onDelete: (project: Project) => void }) {
  return <section>
    <div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><h2 className="section-title">{t.dashboard.projectProgress}</h2><p className="text-xs text-slate-400">{t.dashboard.projectSubtitle}</p></div>{onViewAll && <button onClick={onViewAll} className="text-xs text-violet hover:text-white">{t.dashboard.viewAll}</button>}</div>
    {projects.length === 0 ? <div className="panel empty-state"><span className="empty-icon"><FolderKanban size={22} /></span><p>{t.projects.empty}</p></div> : <div className="grid gap-4 sm:grid-cols-2 2xl:grid-cols-3">{projects.slice(0, 3).map(project => {
      const projectTasks = tasks.filter(task => task.project_id === project.id);
      const progress = projectTasks.length ? Math.round(projectTasks.filter(task => task.status === "completed").length / projectTasks.length * 100) : 0;
      return <article key={project.id} className="project-tile" data-status={project.status}><div className="flex flex-wrap items-start justify-between gap-2"><span className="project-status">{project.status === "planning" ? t.projects.planning : project.status === "in_progress" ? t.projects.inProgress : t.projects.completed}</span><span className="flex items-center gap-2"><span className="priority-badge" data-priority={project.priority}>{t.priority[project.priority]}</span><button onClick={() => onOpen(project)} className="icon-action" aria-label={`${t.projects.view}: ${project.name}`}><Eye size={14} /></button>{canEdit && <><button onClick={() => onEdit(project)} className="icon-action" aria-label={`${t.projects.edit}: ${project.name}`}><Pencil size={13} /></button><button onClick={() => onDelete(project)} className="icon-action text-rose-300 hover:text-rose-200" aria-label={`${t.projects.delete}: ${project.name}`}><Trash2 size={13} /></button></>}</span></div><button onClick={() => onOpen(project)} className="mt-3 block max-w-full text-left"><h3 className="truncate text-base font-semibold tracking-tight hover:text-violet">{project.name}</h3><p className="mt-1 truncate text-xs text-slate-400">{project.description || "—"}</p></button><div className="mt-5 flex justify-between text-[11px]"><span>{t.dashboard.progress}</span><strong>{progress}%</strong></div><div className="mt-2" data-progress={progress >= 80 ? "high" : undefined}><ProgressBar value={progress} color="bg-violet" /></div><div className="mt-4 flex items-center justify-between border-t border-line pt-3"><span className="text-[11px] text-slate-400">{t.dashboard.due}</span><span className="flex items-center gap-1 text-[11px] text-slate-400"><CalendarDays size={13} /> {project.due_date || "—"}</span></div></article>;
    })}</div>}
  </section>;
}
