"use client";

import { CalendarDays, FolderKanban, Pencil, Plus, Trash2, X } from "lucide-react";
import type { Translations } from "@/lib/i18n";
import type { Task } from "./tasks-view";
import { ProjectCompletion } from "./project-completion";

export type Project = { id: string; workspace_id: string; name: string; description: string; status: "planning" | "in_progress" | "completed"; priority: "low" | "medium" | "high"; due_date: string | null; created_at: string };
export type ProjectInput = Pick<Project, "name" | "description" | "priority" | "due_date"> & { status: Project["status"] };

const statusClass = { planning: "border-cyan/25 bg-cyan/10 text-cyan", in_progress: "border-violet/25 bg-violet/15 text-[#c8b5ff]", completed: "border-mint/25 bg-mint/10 text-mint" };

export function ProjectForm({ t, project, submitting, onClose, onSubmit }: { t: Translations; project?: Project | null; submitting: boolean; onClose: () => void; onSubmit: (input: ProjectInput) => Promise<void> }) {
  const initial = project ?? { name: "", description: "", priority: "medium" as const, due_date: null, status: "planning" as const };
  return <div className="modal-backdrop" role="dialog" aria-modal="true"><form onSubmit={async event => { event.preventDefault(); const data = new FormData(event.currentTarget); await onSubmit({ name: String(data.get("name") ?? "").trim(), description: String(data.get("description") ?? "").trim(), priority: String(data.get("priority")) as Project["priority"], status: String(data.get("status")) as Project["status"], due_date: String(data.get("due_date") || "") || null }); }} className="modal-panel"><div className="flex items-center justify-between"><h2 className="section-title">{project ? t.projects.edit : t.projects.create}</h2><button type="button" onClick={onClose} className="icon-action"><X size={18} /></button></div><div className="mt-5 space-y-4"><label className="block text-xs font-medium text-slate-300">{t.projects.name}<input name="name" defaultValue={initial.name} required className="field mt-1.5" /></label><label className="block text-xs font-medium text-slate-300">{t.projects.description}<textarea name="description" defaultValue={initial.description} rows={3} className="field mt-1.5" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-xs font-medium text-slate-300">{t.projects.priority}<select name="priority" defaultValue={initial.priority} className="field mt-1.5"><option value="low">{t.priority.low}</option><option value="medium">{t.priority.medium}</option><option value="high">{t.priority.high}</option></select></label><label className="block text-xs font-medium text-slate-300">{t.projects.dueDate}<input name="due_date" type="date" defaultValue={initial.due_date ?? ""} className="field mt-1.5" /></label></div>{project && <label className="block text-xs font-medium text-slate-300">{t.projects.status}<select name="status" defaultValue={initial.status} className="field mt-1.5"><option value="planning">{t.projects.planning}</option><option value="in_progress">{t.projects.inProgress}</option><option value="completed">{t.projects.completed}</option></select></label>}</div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="btn-ghost">{t.projects.cancel}</button><button disabled={submitting} className="btn-primary">{project ? t.projects.save : t.projects.create}</button></div></form></div>;
}

export function ProjectsView({ t, projects, tasks, canCreate, canEdit, onNew, onEdit, onDelete }: { t: Translations; projects: Project[]; tasks: Task[]; canCreate: boolean; canEdit: boolean; onNew: () => void; onEdit: (project: Project) => void; onDelete: (project: Project) => void }) {
  return <section className="py-2"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="page-heading">{t.projects.title}</h1><p className="page-subtitle">{t.projects.subtitle}</p></div>{canCreate && <button onClick={onNew} className="btn-primary"><Plus size={16} />{t.common.newProject}</button>}</div>{projects.length === 0 ? <div className="panel empty-state mt-6"><span className="empty-icon"><FolderKanban size={22} /></span><p>{t.projects.empty}</p></div> : <div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{projects.map(project => <article key={project.id} className="project-tile" data-status={project.status}><div className="flex items-start justify-between gap-2"><span className={`badge ${statusClass[project.status]}`}>{project.status === "planning" ? t.projects.planning : project.status === "in_progress" ? t.projects.inProgress : t.projects.completed}</span><span className="priority-badge" data-priority={project.priority}>{t.priority[project.priority]}</span></div><h2 className="mt-4 break-words text-base font-semibold tracking-tight">{project.name}</h2><p className="mt-1 min-h-8 text-xs text-slate-400">{project.description || "—"}</p><ProjectCompletion projectId={project.id} tasks={tasks} label={t.projects.progress} /><div className="mt-4 flex items-center justify-between border-t border-line pt-3 text-[11px] text-slate-400"><span className="flex items-center gap-1"><CalendarDays size={13} />{project.due_date ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(`${project.due_date}T00:00:00`)) : "—"}</span>{canEdit && <span className="flex gap-2"><button onClick={() => onEdit(project)} className="icon-action" aria-label={t.projects.edit}><Pencil size={14} /></button><button onClick={() => onDelete(project)} className="icon-action text-rose-300 hover:text-rose-200" aria-label={t.projects.delete}><Trash2 size={14} /></button></span>}</div></article>)}</div>}</section>;
}
