import { ImagePlus, LogOut, Trash2 } from "lucide-react";
import type { Language, Translations } from "@/lib/i18n";

export function SettingsView({ t, language, setLanguage, onLogout, userName = "", userEmail = "" }: { t: Translations; language: Language; setLanguage: (language: Language) => void; onLogout?: () => Promise<{ error: Error | null }>; userName?: string; userEmail?: string }) {
  return <section className="max-w-4xl py-2"><div><h1 className="text-2xl font-bold tracking-tight">{t.settings.title}</h1><p className="mt-1 text-xs leading-5 text-slate-400">{t.settings.subtitle}</p></div>
    <div className="mt-5 space-y-4"><section className="panel p-4"><h2 className="text-base font-semibold">{t.settings.workspace}</h2><div className="mt-4 grid gap-4 sm:grid-cols-[minmax(0,1fr)_180px]"><label className="block text-[11px] font-medium text-slate-300">{t.settings.workspaceName}<input defaultValue={t.workspace.name} className="mt-1.5 h-9 w-full rounded-lg border border-line bg-elevated px-3 text-xs outline-none focus:border-violet focus:ring-1 focus:ring-violet" /></label><div><p className="text-[11px] font-medium text-slate-300">{t.settings.workspaceLogo}</p><div className="mt-1.5 flex h-16 items-center gap-3 rounded-lg border border-dashed border-line bg-elevated px-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-violet/15 text-violet"><ImagePlus size={17} /></span><p className="text-[10px] leading-4 text-slate-400">{t.settings.logoHelper}</p></div></div></div></section>
      <section className="panel p-4"><h2 className="text-base font-semibold">{t.settings.profile}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="block text-[11px] font-medium text-slate-300">{t.settings.name}<input value={userName} readOnly className="mt-1.5 h-9 w-full rounded-lg border border-line bg-elevated px-3 text-xs outline-none focus:border-violet focus:ring-1 focus:ring-violet" /></label><label className="block text-[11px] font-medium text-slate-300">{t.settings.email}<input value={userEmail} readOnly type="email" className="mt-1.5 h-9 w-full rounded-lg border border-line bg-elevated px-3 text-xs outline-none focus:border-violet focus:ring-1 focus:ring-violet" /></label></div></section>
      <section className="panel p-4"><h2 className="text-base font-semibold">{t.settings.preferences}</h2><div className="mt-4"><p className="text-[11px] font-medium text-slate-300">{t.common.language}</p><div className="mt-1.5 inline-flex rounded-lg bg-elevated p-1 text-xs"><button onClick={() => setLanguage("en")} className={`rounded px-3 py-1.5 transition ${language === "en" ? "bg-slate-700 text-white" : "text-slate-400 hover:text-white"}`}>EN · {t.common.english}</button><button onClick={() => setLanguage("es")} className={`rounded px-3 py-1.5 transition ${language === "es" ? "bg-slate-700 text-white" : "text-slate-400 hover:text-white"}`}>ES · {t.common.spanish}</button></div></div></section>
      <section className="panel p-4"><h2 className="text-base font-semibold">{t.settings.account}</h2><div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><button onClick={() => void onLogout?.()} className="flex h-9 w-fit items-center gap-1.5 rounded-lg bg-elevated px-3 text-xs text-slate-200 transition hover:bg-slate-700"><LogOut size={15} />{t.settings.logout}</button><div className="flex items-center gap-3"><p className="text-[10px] text-slate-500">{t.settings.deleteHelper}</p><button className="flex h-9 shrink-0 items-center gap-1.5 rounded-lg border border-rose-400/25 px-3 text-xs text-rose-300 transition hover:bg-rose-400/10"><Trash2 size={15} />{t.settings.deleteAccount}</button></div></div></section>
    </div>
  </section>;
}
