import { ClipboardList, Pencil, Plus, Trash2 } from "lucide-react";
import type { Translations } from "@/lib/i18n";
import type { Project } from "./projects-view";
import { taskStatusLabel, type Task, type TaskStatusValue, type WorkspaceMember } from "./tasks-view";

export function TaskList({ t, tasks, projects, members, canCreate, canEditTask, canDelete, canChangeStatus, onNew, onOpen, onDelete, onStatusChange }: { t: Translations; tasks: Task[]; projects: Project[]; members: WorkspaceMember[]; canCreate: boolean; canEditTask: (task: Task) => boolean; canDelete: boolean; canChangeStatus: (task: Task) => boolean; onNew: () => void; onOpen: (task: Task) => void; onDelete: (task: Task) => void; onStatusChange: (task: Task, status: TaskStatusValue) => void }) {
  const projectNames = new Map(projects.map(project => [project.id, project.name]));
  const memberNames = new Map(members.map(member => [member.user_id, member.name || member.email]));
  return <section className="panel task-surface min-w-0 overflow-hidden"><div className="flex items-center justify-between gap-3 p-5"><div className="flex items-center gap-2"><h2 className="section-title">{t.dashboard.assignedTasks}</h2><span className="rounded-full bg-elevated px-2 py-0.5 text-[11px] text-slate-300">{tasks.length}</span></div>{canCreate && <button onClick={onNew} disabled={projects.length === 0} title={projects.length === 0 ? t.tasks.noProjects : undefined} className="btn-primary min-h-9"><Plus size={14} />{t.tasks.new}</button>}</div>{tasks.length === 0 ? <div className="empty-state"><span className="empty-icon"><ClipboardList size={22} /></span><p className="text-sm text-slate-400">{t.tasks.empty}</p></div> : <div className="overflow-x-auto"><div className="min-w-[720px]"><div className="table-head grid grid-cols-[minmax(180px,1.5fr)_minmax(115px,1fr)_130px_85px_90px] gap-3 "><span>{t.dashboard.task}</span><span>{t.tasks.project}</span><span>{t.dashboard.status}</span><span>{t.tasks.priority}</span><span>{t.team.actions}</span></div>{tasks.slice(0, 6).map(task => <div key={task.id} className="grid grid-cols-[minmax(180px,1.5fr)_minmax(115px,1fr)_130px_85px_90px] items-center gap-3 table-row border-b border-line last:border-0"><div className="min-w-0">{canEditTask(task) ? <button onClick={() => onOpen(task)} className="block max-w-full truncate text-left text-xs font-medium hover:text-violet">{task.title}</button> : <span className="block truncate text-xs font-medium">{task.title}</span>}<span className="block truncate text-[10px] text-slate-500">{task.assignee_id ? memberNames.get(task.assignee_id) ?? "—" : t.tasks.unassigned}</span></div><span className="truncate text-[11px] text-slate-400">{projectNames.get(task.project_id) ?? "—"}</span>{canChangeStatus(task) ? <select value={task.status} onChange={event => onStatusChange(task, event.target.value as TaskStatusValue)} aria-label={`${t.tasks.changeStatus}: ${task.title}`} className="field field-compact"><option value="pending">{t.status.pending}</option><option value="in_progress">{t.status.inProgress}</option><option value="completed">{t.status.completed}</option></select> : <span className="text-[11px]">{taskStatusLabel(t, task.status)}</span>}<span className="priority-badge" data-priority={task.priority}>{t.priority[task.priority]}</span><span className="flex gap-2">{canEditTask(task) && <button onClick={() => onOpen(task)} className="icon-action" aria-label={`${t.tasks.edit}: ${task.title}`}><Pencil size={14} /></button>}{canDelete && <button onClick={() => onDelete(task)} className="icon-action text-rose-300 hover:text-rose-200" aria-label={`${t.tasks.delete}: ${task.title}`}><Trash2 size={14} /></button>}</span></div>)}</div></div>}</section>;
}
